/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrintingRouteImport } from './routes/printing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollegeKitsIndexRouteImport } from './routes/college-kits.index'
import { Route as ClassKitsIndexRouteImport } from './routes/class-kits.index'
import { Route as CollegeKitsKitIdRouteImport } from './routes/college-kits.$kitId'
import { Route as ClassKitsClassIdRouteImport } from './routes/class-kits.$classId'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintingRoute = PrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeKitsIndexRoute = CollegeKitsIndexRouteImport.update({
  id: '/college-kits/',
  path: '/college-kits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassKitsIndexRoute = ClassKitsIndexRouteImport.update({
  id: '/class-kits/',
  path: '/class-kits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeKitsKitIdRoute = CollegeKitsKitIdRouteImport.update({
  id: '/college-kits/$kitId',
  path: '/college-kits/$kitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassKitsClassIdRoute = ClassKitsClassIdRouteImport.update({
  id: '/class-kits/$classId',
  path: '/class-kits/$classId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/printing': typeof PrintingRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/class-kits/$classId': typeof ClassKitsClassIdRoute
  '/college-kits/$kitId': typeof CollegeKitsKitIdRoute
  '/class-kits/': typeof ClassKitsIndexRoute
  '/college-kits/': typeof CollegeKitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/printing': typeof PrintingRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/class-kits/$classId': typeof ClassKitsClassIdRoute
  '/college-kits/$kitId': typeof CollegeKitsKitIdRoute
  '/class-kits': typeof ClassKitsIndexRoute
  '/college-kits': typeof CollegeKitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/printing': typeof PrintingRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/class-kits/$classId': typeof ClassKitsClassIdRoute
  '/college-kits/$kitId': typeof CollegeKitsKitIdRoute
  '/class-kits/': typeof ClassKitsIndexRoute
  '/college-kits/': typeof CollegeKitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/printing'
    | '/profile'
    | '/shop'
    | '/class-kits/$classId'
    | '/college-kits/$kitId'
    | '/class-kits/'
    | '/college-kits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/printing'
    | '/profile'
    | '/shop'
    | '/class-kits/$classId'
    | '/college-kits/$kitId'
    | '/class-kits'
    | '/college-kits'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/printing'
    | '/profile'
    | '/shop'
    | '/class-kits/$classId'
    | '/college-kits/$kitId'
    | '/class-kits/'
    | '/college-kits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRoute
  PrintingRoute: typeof PrintingRoute
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  ClassKitsClassIdRoute: typeof ClassKitsClassIdRoute
  CollegeKitsKitIdRoute: typeof CollegeKitsKitIdRoute
  ClassKitsIndexRoute: typeof ClassKitsIndexRoute
  CollegeKitsIndexRoute: typeof CollegeKitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printing': {
      id: '/printing'
      path: '/printing'
      fullPath: '/printing'
      preLoaderRoute: typeof PrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-kits/': {
      id: '/college-kits/'
      path: '/college-kits'
      fullPath: '/college-kits/'
      preLoaderRoute: typeof CollegeKitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-kits/': {
      id: '/class-kits/'
      path: '/class-kits'
      fullPath: '/class-kits/'
      preLoaderRoute: typeof ClassKitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-kits/$kitId': {
      id: '/college-kits/$kitId'
      path: '/college-kits/$kitId'
      fullPath: '/college-kits/$kitId'
      preLoaderRoute: typeof CollegeKitsKitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-kits/$classId': {
      id: '/class-kits/$classId'
      path: '/class-kits/$classId'
      fullPath: '/class-kits/$classId'
      preLoaderRoute: typeof ClassKitsClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRoute,
  PrintingRoute: PrintingRoute,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  ClassKitsClassIdRoute: ClassKitsClassIdRoute,
  CollegeKitsKitIdRoute: CollegeKitsKitIdRoute,
  ClassKitsIndexRoute: ClassKitsIndexRoute,
  CollegeKitsIndexRoute: CollegeKitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
